name: Update Submodule

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # Ensure submodules are checked out

      - name: Update submodule
        run: |
          git submodule update --remote
          git add .
          git commit -m "Update submodule to latest commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
